-- 오늘 뭐하지? 전체 Supabase 스키마
-- 신규/기존 프로젝트 모두 SQL Editor에서 이 파일 하나만 실행합니다.
-- 기존 테이블과 데이터는 삭제하지 않으며 반복 실행할 수 있습니다.

begin;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  nickname text,
  region text,
  avatar_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.activities (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  activity_type text not null check (activity_type in ('outdoor', 'home')),
  category text not null,
  duration_minutes integer check (duration_minutes is null or duration_minutes > 0),
  cost_level integer not null default 0 check (cost_level >= 0),
  cost integer not null default 0 check (cost >= 0),
  weather_type text default 'any',
  companion_types jsonb not null default '[]'::jsonb,
  image_url text,
  is_active boolean not null default true,
  is_fixed_time boolean not null default false,
  fixed_start_time time,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.plans (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  plan_date date not null default current_date,
  title text not null,
  style text,
  region text,
  start_time text,
  end_time text,
  total_cost integer not null default 0 check (total_cost >= 0),
  total_distance_km numeric(8,2) not null default 0,
  total_travel_minutes integer not null default 0,
  companion_type text,
  budget integer check (budget is null or budget >= 0),
  activity_mode text,
  weather_summary text,
  status text not null default 'saved',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.plan_items (
  id bigint generated by default as identity primary key,
  plan_id bigint not null references public.plans(id) on delete cascade,
  activity_id text,
  title text not null,
  activity_type text,
  start_time text,
  end_time text,
  fixed_time boolean not null default false,
  duration_minutes integer check (duration_minutes is null or duration_minutes > 0),
  cost integer not null default 0 check (cost >= 0),
  sort_order integer not null default 0,
  location_name text,
  address text,
  source text,
  latitude double precision,
  longitude double precision,
  travel_minutes integer not null default 0,
  distance_km numeric(8,2) not null default 0,
  transport_mode text not null default 'estimate',
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.user_preferences (
  id bigint generated by default as identity primary key,
  user_id uuid not null unique references auth.users(id) on delete cascade,
  default_region text default '부산',
  budget_level integer default 50000 check (budget_level >= 0),
  companion_type text default 'alone',
  interests jsonb not null default '[]'::jsonb,
  favorite_teams jsonb not null default '[]'::jsonb,
  ott_services jsonb not null default '[]'::jsonb,
  activity_mode text default 'balanced',
  transport_mode text default 'car',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.favorites (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  content_type text not null,
  content_id text not null,
  title text not null,
  image_url text,
  source text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  unique (user_id, content_type, content_id)
);

create table if not exists public.user_sports (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  sport_type text not null,
  league text,
  team_id text,
  team_name text not null,
  created_at timestamptz not null default now(),
  unique (user_id, sport_type, league, team_id)
);

create table if not exists public.user_ott_services (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  provider_id text,
  provider_name text not null,
  created_at timestamptz not null default now(),
  unique (user_id, provider_name)
);

-- 과거 Day SQL로 만든 DB의 누락 확장 컬럼을 보충합니다.
alter table public.profiles add column if not exists avatar_url text;
alter table public.profiles add column if not exists updated_at timestamptz not null default now();
alter table public.activities add column if not exists cost integer not null default 0;
alter table public.activities add column if not exists is_fixed_time boolean not null default false;
alter table public.activities add column if not exists fixed_start_time time;
alter table public.activities add column if not exists updated_at timestamptz not null default now();
alter table public.plans add column if not exists total_distance_km numeric(8,2) not null default 0;
alter table public.plans add column if not exists total_travel_minutes integer not null default 0;
alter table public.plans add column if not exists companion_type text;
alter table public.plans add column if not exists budget integer;
alter table public.plans add column if not exists activity_mode text;
alter table public.plans add column if not exists weather_summary text;
alter table public.plans add column if not exists status text not null default 'saved';
alter table public.plans add column if not exists updated_at timestamptz not null default now();
alter table public.plan_items add column if not exists duration_minutes integer;
alter table public.plan_items add column if not exists location_name text;
alter table public.plan_items add column if not exists address text;
alter table public.plan_items add column if not exists source text;
alter table public.plan_items add column if not exists latitude double precision;
alter table public.plan_items add column if not exists longitude double precision;
alter table public.plan_items add column if not exists travel_minutes integer not null default 0;
alter table public.plan_items add column if not exists distance_km numeric(8,2) not null default 0;
alter table public.plan_items add column if not exists transport_mode text not null default 'estimate';

create index if not exists activities_active_category_idx on public.activities(category) where is_active = true;
create index if not exists plans_user_created_at_idx on public.plans(user_id, created_at desc);
create index if not exists plans_user_date_idx on public.plans(user_id, plan_date desc);
create index if not exists plan_items_plan_sort_idx on public.plan_items(plan_id, sort_order);
create unique index if not exists user_preferences_user_id_unique on public.user_preferences(user_id);
create index if not exists favorites_user_created_idx on public.favorites(user_id, created_at desc);
create index if not exists user_sports_user_idx on public.user_sports(user_id);
create index if not exists user_ott_services_user_idx on public.user_ott_services(user_id);

alter table public.profiles enable row level security;
alter table public.activities enable row level security;
alter table public.plans enable row level security;
alter table public.plan_items enable row level security;
alter table public.user_preferences enable row level security;
alter table public.favorites enable row level security;
alter table public.user_sports enable row level security;
alter table public.user_ott_services enable row level security;

drop policy if exists "activities public read" on public.activities;
create policy "activities public read" on public.activities for select using (is_active = true);

drop policy if exists "Users manage own profile" on public.profiles;
create policy "Users manage own profile" on public.profiles for all to authenticated
  using ((select auth.uid()) = id) with check ((select auth.uid()) = id);

drop policy if exists "Users manage own plans" on public.plans;
create policy "Users manage own plans" on public.plans for all to authenticated
  using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);

drop policy if exists "Users manage own plan items" on public.plan_items;
create policy "Users manage own plan items" on public.plan_items for all to authenticated
  using (exists (select 1 from public.plans p where p.id = plan_items.plan_id and p.user_id = (select auth.uid())))
  with check (exists (select 1 from public.plans p where p.id = plan_items.plan_id and p.user_id = (select auth.uid())));

drop policy if exists "Users manage own preferences" on public.user_preferences;
create policy "Users manage own preferences" on public.user_preferences for all to authenticated
  using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);

drop policy if exists "Users manage own favorites" on public.favorites;
create policy "Users manage own favorites" on public.favorites for all to authenticated
  using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);

drop policy if exists "Users manage own sports" on public.user_sports;
create policy "Users manage own sports" on public.user_sports for all to authenticated
  using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);

drop policy if exists "Users manage own ott services" on public.user_ott_services;
create policy "Users manage own ott services" on public.user_ott_services for all to authenticated
  using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);

-- 이전 파일에서 생성한 정책을 제거해 중복 평가를 막습니다.
drop policy if exists "Users can view own profile" on public.profiles;
drop policy if exists "Users can create own profile" on public.profiles;
drop policy if exists "Users can update own profile" on public.profiles;
drop policy if exists "Users can view own plans" on public.plans;
drop policy if exists "Users can create own plans" on public.plans;
drop policy if exists "Users can update own plans" on public.plans;
drop policy if exists "Users can delete own plans" on public.plans;
drop policy if exists "Users can view own plan items" on public.plan_items;
drop policy if exists "Users can create own plan items" on public.plan_items;
drop policy if exists "Users can update own plan items" on public.plan_items;
drop policy if exists "Users can delete own plan items" on public.plan_items;
drop policy if exists "Users can view own preferences" on public.user_preferences;
drop policy if exists "Users can create own preferences" on public.user_preferences;
drop policy if exists "Users can update own preferences" on public.user_preferences;
drop policy if exists "Users can delete own preferences" on public.user_preferences;

create or replace function public.set_updated_at()
returns trigger language plpgsql set search_path = '' as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists profiles_set_updated_at on public.profiles;
create trigger profiles_set_updated_at before update on public.profiles for each row execute function public.set_updated_at();
drop trigger if exists activities_set_updated_at on public.activities;
create trigger activities_set_updated_at before update on public.activities for each row execute function public.set_updated_at();
drop trigger if exists plans_set_updated_at on public.plans;
create trigger plans_set_updated_at before update on public.plans for each row execute function public.set_updated_at();
drop trigger if exists preferences_set_updated_at on public.user_preferences;
create trigger preferences_set_updated_at before update on public.user_preferences for each row execute function public.set_updated_at();

insert into public.activities (title, description, activity_type, category, duration_minutes, cost_level, weather_type)
select seed.* from (values
  ('동네 산책', '날씨가 좋을 때 가까운 곳을 가볍게 걸어보세요.', 'outdoor', 'walk', 60, 0, 'sunny'),
  ('영화관에서 영화 보기', '현재 상영작과 상영시간을 확인합니다.', 'outdoor', 'cinema', 150, 2, 'any'),
  ('OTT 영화 한 편', '집에서 OTT 영화를 감상합니다.', 'home', 'ott', 120, 1, 'any'),
  ('30분 독서', '조용하게 책을 읽습니다.', 'home', 'book', 30, 0, 'any'),
  ('오늘의 요리', '한 끼를 직접 만들어봅니다.', 'home', 'cooking', 60, 1, 'any'),
  ('스포츠 경기 시청', '관심팀 경기를 시청합니다.', 'home', 'sports', 150, 0, 'any'),
  ('필드 골프', '예약한 골프장에서 라운드합니다.', 'outdoor', 'golf-field', 300, 4, 'sunny'),
  ('스크린골프', '실내 스크린골프장에서 즐깁니다.', 'outdoor', 'golf-screen', 120, 2, 'any')
) as seed(title, description, activity_type, category, duration_minutes, cost_level, weather_type)
where not exists (
  select 1 from public.activities existing where existing.title = seed.title and existing.category = seed.category
);

commit;

select tablename, rowsecurity
from pg_tables
where schemaname = 'public'
  and tablename in ('profiles','activities','plans','plan_items','user_preferences','favorites','user_sports','user_ott_services')
order by tablename;
