-- 1~3일차 확정 IA/DB 구조를 기존 DAY 20 DB에 안전하게 추가합니다.
-- 기존 day12.sql, day20.sql 실행 후 적용하세요.

begin;

alter table public.profiles add column if not exists avatar_url text;
alter table public.profiles add column if not exists updated_at timestamptz not null default now();

create table if not exists public.activities (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  activity_type text not null check (activity_type in ('outdoor', 'home')),
  category text not null,
  duration_minutes integer check (duration_minutes is null or duration_minutes > 0),
  cost_level integer not null default 0 check (cost_level >= 0),
  weather_type text default 'any',
  companion_types jsonb not null default '[]'::jsonb,
  image_url text,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

alter table public.activities add column if not exists cost integer not null default 0 check (cost >= 0);
alter table public.activities add column if not exists is_fixed_time boolean not null default false;
alter table public.activities add column if not exists fixed_start_time time;
alter table public.activities add column if not exists updated_at timestamptz not null default now();

alter table public.activities enable row level security;
drop policy if exists "activities public read" on public.activities;
create policy "activities public read" on public.activities for select
using (is_active = true);

insert into public.activities (title, description, activity_type, category, duration_minutes, cost_level, weather_type)
select seed.title, seed.description, seed.activity_type, seed.category, seed.duration_minutes, seed.cost_level, seed.weather_type
from (values
  ('동네 산책', '날씨가 좋을 때 가까운 곳을 가볍게 걸어보세요.', 'outdoor', 'walk', 60, 0, 'sunny'),
  ('영화관에서 영화 보기', '현재 상영작과 상영시간을 확인해 영화관에서 관람합니다.', 'outdoor', 'cinema', 150, 2, 'any'),
  ('OTT 영화 한 편', '집에서 편안하게 OTT 영화 한 편을 감상합니다.', 'home', 'ott', 120, 1, 'any'),
  ('30분 독서', '조용하게 책을 읽으며 시간을 보냅니다.', 'home', 'book', 30, 0, 'any'),
  ('오늘의 요리', '한 끼를 직접 만들어봅니다.', 'home', 'cooking', 60, 1, 'any'),
  ('스포츠 경기 시청', '관심팀 경기를 일정에 넣어 시청합니다.', 'home', 'sports', 150, 0, 'any')
) as seed(title, description, activity_type, category, duration_minutes, cost_level, weather_type)
where not exists (
  select 1 from public.activities existing where existing.title = seed.title and existing.category = seed.category
);

create table if not exists public.favorites (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  content_type text not null,
  content_id text not null,
  title text not null,
  image_url text,
  source text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  unique (user_id, content_type, content_id)
);

create table if not exists public.user_sports (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  sport_type text not null,
  league text,
  team_id text,
  team_name text not null,
  created_at timestamptz not null default now(),
  unique (user_id, sport_type, league, team_id)
);

create table if not exists public.user_ott_services (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  provider_id text,
  provider_name text not null,
  created_at timestamptz not null default now(),
  unique (user_id, provider_name)
);

alter table public.plans add column if not exists companion_type text;
alter table public.plans add column if not exists budget integer check (budget is null or budget >= 0);
alter table public.plans add column if not exists activity_mode text;
alter table public.plans add column if not exists weather_summary text;
alter table public.plans add column if not exists status text not null default 'saved';
alter table public.plans add column if not exists updated_at timestamptz not null default now();

alter table public.plan_items add column if not exists duration_minutes integer check (duration_minutes is null or duration_minutes > 0);
alter table public.plan_items add column if not exists location_name text;
alter table public.plan_items add column if not exists address text;
alter table public.plan_items add column if not exists source text;

create index if not exists favorites_user_created_idx on public.favorites(user_id, created_at desc);
create index if not exists user_sports_user_idx on public.user_sports(user_id);
create index if not exists user_ott_services_user_idx on public.user_ott_services(user_id);

alter table public.favorites enable row level security;
alter table public.user_sports enable row level security;
alter table public.user_ott_services enable row level security;

drop policy if exists "Users manage own favorites" on public.favorites;
create policy "Users manage own favorites" on public.favorites for all to authenticated
using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);

drop policy if exists "Users manage own sports" on public.user_sports;
create policy "Users manage own sports" on public.user_sports for all to authenticated
using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);

drop policy if exists "Users manage own ott services" on public.user_ott_services;
create policy "Users manage own ott services" on public.user_ott_services for all to authenticated
using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);

commit;
