-- 1~3일차 확정 IA/DB 구조를 기존 DAY 20 DB에 안전하게 추가합니다.
-- 기존 day12.sql, day20.sql 실행 후 적용하세요.

begin;

alter table public.profiles add column if not exists avatar_url text;
alter table public.profiles add column if not exists updated_at timestamptz not null default now();

alter table public.activities add column if not exists cost integer not null default 0 check (cost >= 0);
alter table public.activities add column if not exists is_fixed_time boolean not null default false;
alter table public.activities add column if not exists fixed_start_time time;
alter table public.activities add column if not exists updated_at timestamptz not null default now();

create table if not exists public.favorites (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  content_type text not null,
  content_id text not null,
  title text not null,
  image_url text,
  source text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  unique (user_id, content_type, content_id)
);

create table if not exists public.user_sports (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  sport_type text not null,
  league text,
  team_id text,
  team_name text not null,
  created_at timestamptz not null default now(),
  unique (user_id, sport_type, league, team_id)
);

create table if not exists public.user_ott_services (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  provider_id text,
  provider_name text not null,
  created_at timestamptz not null default now(),
  unique (user_id, provider_name)
);

alter table public.plans add column if not exists companion_type text;
alter table public.plans add column if not exists budget integer check (budget is null or budget >= 0);
alter table public.plans add column if not exists activity_mode text;
alter table public.plans add column if not exists weather_summary text;
alter table public.plans add column if not exists status text not null default 'saved';
alter table public.plans add column if not exists updated_at timestamptz not null default now();

alter table public.plan_items add column if not exists duration_minutes integer check (duration_minutes is null or duration_minutes > 0);
alter table public.plan_items add column if not exists location_name text;
alter table public.plan_items add column if not exists address text;
alter table public.plan_items add column if not exists source text;

create index if not exists favorites_user_created_idx on public.favorites(user_id, created_at desc);
create index if not exists user_sports_user_idx on public.user_sports(user_id);
create index if not exists user_ott_services_user_idx on public.user_ott_services(user_id);

alter table public.favorites enable row level security;
alter table public.user_sports enable row level security;
alter table public.user_ott_services enable row level security;

drop policy if exists "Users manage own favorites" on public.favorites;
create policy "Users manage own favorites" on public.favorites for all to authenticated
using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);

drop policy if exists "Users manage own sports" on public.user_sports;
create policy "Users manage own sports" on public.user_sports for all to authenticated
using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);

drop policy if exists "Users manage own ott services" on public.user_ott_services;
create policy "Users manage own ott services" on public.user_ott_services for all to authenticated
using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);

commit;
