create table if not exists activities (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  activity_type text not null check (activity_type in ('outdoor','home')),
  category text not null,
  duration_minutes integer,
  cost_level integer default 0,
  weather_type text default 'any',
  companion_types jsonb default '[]'::jsonb,
  image_url text,
  is_active boolean default true,
  created_at timestamptz default now()
);

alter table activities enable row level security;

drop policy if exists "activities public read" on activities;
create policy "activities public read"
on activities for select
using (is_active = true);

insert into activities (title, description, activity_type, category, duration_minutes, cost_level, weather_type)
values
('동네 산책', '날씨가 좋을 때 가까운 곳을 가볍게 걸어보세요.', 'outdoor', 'walk', 60, 0, 'sunny'),
('영화관에서 영화 보기', '현재 상영작과 상영시간을 확인해 영화관에서 관람합니다.', 'outdoor', 'cinema', 150, 2, 'any'),
('OTT 영화 한 편', '집에서 편안하게 OTT 영화 한 편을 감상합니다.', 'home', 'ott', 120, 1, 'any'),
('30분 독서', '조용하게 책을 읽으며 시간을 보냅니다.', 'home', 'book', 30, 0, 'any'),
('오늘의 요리', '식품안전나라 레시피를 활용해 한 끼를 만들어봅니다.', 'home', 'cooking', 60, 1, 'any'),
('스포츠 경기 시청', '오늘 열리는 관심팀 경기를 일정에 넣어 시청합니다.', 'home', 'sports', 150, 0, 'any');
