-- 오늘 뭐하지? Day 12 Supabase 통합 SQL
-- Supabase > SQL Editor > New query 에서 전체 실행

begin;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  nickname text,
  region text,
  created_at timestamptz not null default now()
);

create table if not exists public.plans (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  plan_date date not null default current_date,
  title text not null,
  style text,
  region text,
  start_time text,
  end_time text,
  total_cost integer not null default 0 check (total_cost >= 0),
  created_at timestamptz not null default now()
);

create table if not exists public.plan_items (
  id bigint generated by default as identity primary key,
  plan_id bigint not null references public.plans(id) on delete cascade,
  activity_id text,
  title text not null,
  activity_type text,
  start_time text,
  end_time text,
  fixed_time boolean not null default false,
  cost integer not null default 0 check (cost >= 0),
  sort_order integer not null default 0,
  metadata jsonb,
  created_at timestamptz not null default now()
);

create index if not exists plans_user_id_idx on public.plans(user_id);
create index if not exists plans_user_created_at_idx on public.plans(user_id, created_at desc);
create index if not exists plan_items_plan_id_idx on public.plan_items(plan_id);
create index if not exists plan_items_plan_sort_idx on public.plan_items(plan_id, sort_order);

alter table public.profiles enable row level security;
alter table public.plans enable row level security;
alter table public.plan_items enable row level security;

drop policy if exists "Users can view own profile" on public.profiles;
drop policy if exists "Users can create own profile" on public.profiles;
drop policy if exists "Users can update own profile" on public.profiles;

create policy "Users can view own profile"
on public.profiles for select to authenticated
using ((select auth.uid()) = id);

create policy "Users can create own profile"
on public.profiles for insert to authenticated
with check ((select auth.uid()) = id);

create policy "Users can update own profile"
on public.profiles for update to authenticated
using ((select auth.uid()) = id)
with check ((select auth.uid()) = id);

drop policy if exists "Users can view own plans" on public.plans;
drop policy if exists "Users can create own plans" on public.plans;
drop policy if exists "Users can update own plans" on public.plans;
drop policy if exists "Users can delete own plans" on public.plans;

create policy "Users can view own plans"
on public.plans for select to authenticated
using ((select auth.uid()) = user_id);

create policy "Users can create own plans"
on public.plans for insert to authenticated
with check ((select auth.uid()) = user_id);

create policy "Users can update own plans"
on public.plans for update to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

create policy "Users can delete own plans"
on public.plans for delete to authenticated
using ((select auth.uid()) = user_id);

drop policy if exists "Users can view own plan items" on public.plan_items;
drop policy if exists "Users can create own plan items" on public.plan_items;
drop policy if exists "Users can update own plan items" on public.plan_items;
drop policy if exists "Users can delete own plan items" on public.plan_items;

create policy "Users can view own plan items"
on public.plan_items for select to authenticated
using (
  exists (
    select 1 from public.plans p
    where p.id = plan_items.plan_id
      and p.user_id = (select auth.uid())
  )
);

create policy "Users can create own plan items"
on public.plan_items for insert to authenticated
with check (
  exists (
    select 1 from public.plans p
    where p.id = plan_items.plan_id
      and p.user_id = (select auth.uid())
  )
);

create policy "Users can update own plan items"
on public.plan_items for update to authenticated
using (
  exists (
    select 1 from public.plans p
    where p.id = plan_items.plan_id
      and p.user_id = (select auth.uid())
  )
)
with check (
  exists (
    select 1 from public.plans p
    where p.id = plan_items.plan_id
      and p.user_id = (select auth.uid())
  )
);

create policy "Users can delete own plan items"
on public.plan_items for delete to authenticated
using (
  exists (
    select 1 from public.plans p
    where p.id = plan_items.plan_id
      and p.user_id = (select auth.uid())
  )
);

commit;

-- 생성 확인
select table_name
from information_schema.tables
where table_schema = 'public'
  and table_name in ('profiles', 'plans', 'plan_items')
order by table_name;
