-- 오늘 뭐하지? DAY 13~20 통합 확장 SQL
-- DAY12 SQL 실행 후 이 파일을 실행하세요.

create table if not exists public.user_preferences (
  id bigint generated by default as identity primary key,
  user_id uuid not null unique references auth.users(id) on delete cascade,
  default_region text default '부산',
  budget_level integer default 50000 check (budget_level >= 0),
  companion_type text default 'alone',
  interests jsonb not null default '[]'::jsonb,
  favorite_teams jsonb not null default '[]'::jsonb,
  ott_services jsonb not null default '[]'::jsonb,
  activity_mode text default 'balanced',
  transport_mode text default 'car',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.user_preferences enable row level security;

drop policy if exists "Users can view own preferences" on public.user_preferences;
drop policy if exists "Users can create own preferences" on public.user_preferences;
drop policy if exists "Users can update own preferences" on public.user_preferences;
drop policy if exists "Users can delete own preferences" on public.user_preferences;

create policy "Users can view own preferences"
on public.user_preferences for select to authenticated
using ((select auth.uid()) = user_id);

create policy "Users can create own preferences"
on public.user_preferences for insert to authenticated
with check ((select auth.uid()) = user_id);

create policy "Users can update own preferences"
on public.user_preferences for update to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

create policy "Users can delete own preferences"
on public.user_preferences for delete to authenticated
using ((select auth.uid()) = user_id);

create index if not exists user_preferences_user_id_idx on public.user_preferences(user_id);

alter table public.plans add column if not exists total_distance_km numeric(8,2) default 0;
alter table public.plans add column if not exists total_travel_minutes integer default 0;

alter table public.plan_items add column if not exists latitude double precision;
alter table public.plan_items add column if not exists longitude double precision;
alter table public.plan_items add column if not exists travel_minutes integer default 0;
alter table public.plan_items add column if not exists distance_km numeric(8,2) default 0;
alter table public.plan_items add column if not exists transport_mode text default 'estimate';

select table_name
from information_schema.tables
where table_schema = 'public'
  and table_name in ('profiles','plans','plan_items','user_preferences')
order by table_name;
